- name: conditions
  hosts: local
  connection: local
  vars:
    number: 15
  tasks:
  - name: check the number is less then 10 or not
    ansible.builtin.debug:
      msg: "Entered Number:{{ number }} is less than 10"
    when: number < 10
