- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print name
    ansible.builtin.debug:
      msg: "Hellooo {{ item }}" # item is reserved
    loop:
    - Ramesh
    - Raju
    - Rambabu
    - Rajiv
