- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print packages 
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - stress
    - zip

